USE [master]
GO

/****** Object:  Database [QbixTest]    Script Date: 21.01.2022 9:54:18 ******/
CREATE DATABASE [QbixTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QbixTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\QbixTest.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'QbixTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\QbixTest_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [QbixTest] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QbixTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QbixTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QbixTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QbixTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QbixTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QbixTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [QbixTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QbixTest] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [QbixTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QbixTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QbixTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QbixTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QbixTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QbixTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QbixTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QbixTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QbixTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QbixTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QbixTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QbixTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QbixTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QbixTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QbixTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QbixTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QbixTest] SET RECOVERY FULL 
GO

ALTER DATABASE [QbixTest] SET  MULTI_USER 
GO

ALTER DATABASE [QbixTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QbixTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QbixTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QbixTest] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [QbixTest] SET  READ_WRITE 
GO


